# Generated by Django 3.1.7 on 2021-07-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IT', models.CharField(max_length=20)),
                ('Mechanical', models.CharField(max_length=20)),
                ('Electrical', models.CharField(max_length=20)),
                ('Teachers', models.CharField(max_length=20)),
            ],
        ),
    ]
