# Generated by Django 3.1.7 on 2021-07-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporting_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='FacDepartment',
        ),
    ]
